package routes

import (
	"altar-app/application/config"
	"altar-app/infrastructure/auth"
	"altar-app/infrastructure/persistence"
	"altar-app/interfaces/handler"
	"altar-app/interfaces/middleware"
	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"log"
	"os"

	"altar-app/docs" // docs is generated by Swag CLI, you have to import it.
)

//API : Handler API Interfacing to FrontEnd
func API() {
	if err := godotenv.Load(); err != nil {
		log.Println("no env gotten")
	}

	conf := config.LoadAppConfig("postgres")
	dbdriver := conf.Driver
	host := conf.Host
	password := conf.Password
	user := conf.User
	dbname := conf.DBName
	port := conf.Port

	//redis details
	confRedis := config.LoadAppConfig("redis")
	redisHost := confRedis.Host
	redisPort := confRedis.Port
	redisPassword := confRedis.Password

	services, err := persistence.NewRepositories(dbdriver, user, password, port, host, dbname)
	if err != nil {
		panic(err)
	}
	defer services.Close()
	services.Automigrate()

	redisService, err := auth.NewRedisDB(redisHost, redisPort, redisPassword)
	if err != nil {
		log.Fatal(err)
	}

	tk := auth.NewToken()

	users := interfaces.NewUsers(services.User, redisService.Auth, tk)
	roles := interfaces.NewRoles(services.Role, redisService.Auth, tk)
	pelanggans := interfaces.NewPelanggans(services.Pelanggan, services.Penagihan, services.User, redisService.Auth, tk)
	penagihans := interfaces.NewPenagihans(services.Penagihan, services.User, services.Transaksi, redisService.Auth, tk)
	petugas := interfaces.NewPetugass(services.Petugas, services.Penagihan, services.User, redisService.Auth, tk)
	transactions := interfaces.NewTransactions(services.Transaksi, services.User, redisService.Auth, tk)
	authenticate := interfaces.NewAuthenticate(services.User, redisService.Auth, tk)

	// @contact.name API Support
	// @contact.url http://www.swagger.io/support
	// @contact.email support@swagger.io

	// @license.name Apache 2.0
	// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

	// @termsOfService http://swagger.io/terms/

	r := gin.Default()
	r.Use(middleware.CORSMiddleware()) //For CORS

	// programmatically set swagger info
	docs.SwaggerInfo.Title = "AD Example API"
	docs.SwaggerInfo.Description = "This is a sample server Petstore server."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "petstore.swagger.io"
	docs.SwaggerInfo.BasePath = "/v2"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	url := ginSwagger.URL("http://localhost:1123/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	v1 := r.Group("/v1/api")
	//user routes
	v1.POST("/users", middleware.AuthMiddleware(), users.SaveUser)
	v1.GET("/users", users.GetUsers)
	v1.GET("/users/:user_id", users.GetUser)

	//role routes
	v1.GET("/roles", middleware.AuthMiddleware(), roles.GetRoles)

	//pelanggans routes
	v1.GET("/pelanggans", middleware.AuthMiddleware(), pelanggans.GetPelanggans)
	v1.GET("/pelanggans/:nosamb/tagihan", middleware.AuthMiddleware(), pelanggans.GetTagihanPelanggan)

	//penagihans routes
	penagihanRoute := r.Group("/v1/api/penagihan")
	penagihanRoute.GET("/", middleware.AuthMiddleware(), penagihans.GetPenagihans)
	penagihanRoute.POST("/bayar_sync", middleware.AuthMiddleware(), penagihans.BayarTagihanPelangganBulk)
	penagihanRoute.POST("/bayar", middleware.AuthMiddleware(), penagihans.BayarTagihanPelanggan)

	//transactions routes
	v1.POST("/transactions", middleware.AuthMiddleware(), transactions.GetTransactions)

	//petugas routes
	petugasRoute := r.Group("/v1/api/petugas")
	petugasRoute.GET("/get_data", middleware.AuthMiddleware(), petugas.GetDataPetugas)
	petugasRoute.GET("/petugas/profile", middleware.AuthMiddleware(), petugas.GetProfilePetugas)

	//pelanggan routes
	pelangganRoute := r.Group("/v1/api/pelanggan")
	pelangganRoute.GET("/inquiry_loket", middleware.AuthMiddleware(), pelanggans.InquiryLoketTagihanPelanggan)

	//authentication routes
	v1.POST("/login", authenticate.Login)
	v1.POST("/logout", authenticate.Logout)
	v1.POST("/refresh", authenticate.Refresh)

	//Starting the application
	appPort := os.Getenv("PORT") //using heroku host
	if appPort == "" {
		appPort = "1123" //localhost
	}
	log.Fatal(r.Run(":" + appPort))
}
