// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get_data": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves petigas data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.PetugasData"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Retrieves user based on given ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Drd": {
            "type": "object",
            "properties": {
                "nosamb": {
                    "type": "string"
                },
                "periode": {
                    "type": "string"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "entity.PenagihansSrKolektif": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "kode_pdam": {
                    "type": "string"
                },
                "kolektif": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "nosamb": {
                    "type": "string"
                },
                "notelp": {
                    "type": "string"
                },
                "pdam": {
                    "type": "string"
                },
                "periode_kolektif": {
                    "type": "string"
                },
                "periode_tagihan": {
                    "type": "string"
                },
                "rayon_name": {
                    "type": "string"
                },
                "status_billing": {
                    "type": "string"
                },
                "status_kolektif": {
                    "type": "string"
                },
                "status_pelanggan": {
                    "type": "string"
                },
                "tagihan_air": {
                    "type": "integer"
                },
                "tagihan_nonair": {
                    "type": "integer"
                },
                "total_administrasi": {
                    "type": "number"
                },
                "total_denda": {
                    "type": "number"
                },
                "total_tagihan": {
                    "type": "number"
                },
                "total_tagihan_air": {
                    "type": "number"
                },
                "total_tagihan_nonair": {
                    "type": "number"
                }
            }
        },
        "entity.PetugasData": {
            "type": "object",
            "properties": {
                "penagihan_billing": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Drd"
                    }
                },
                "penagihan_pelanggan": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.PenagihansSrKolektif"
                    }
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "pdam": {
                    "type": "string"
                },
                "pin": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
