name: Go

on:
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/altar-app

    - name: Get dependencies
      run: |
        cd ${GOPATH}/src/altar-app
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      env:
        GOPATH: /home/runner/work/altar-app/altar-app/go

    - name: Build
      run: |
        cd ${GOPATH}/src/altar-app
        env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build
        echo "${{ github.event.release.tag_name }}"
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        cp docker/dockerfile-api Dockerfile
        docker build -t ${{ secrets.DOCKER_USERNAME }}/altar-app:${{ github.event.release.tag_name }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/altar-app:${{ github.event.release.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        GOPATH: /home/runner/work/altar-app/altar-app/go
